### ISSUE TITLE
What is the licence for this repository?

### ISSUE THREAD

**Issue by andybak** [loOong-Cheng/Adaptive-Shader-for-Point-Cloud-ply-#1]
Pcx used Unlicense but a standard OSI approved licence would be preferable. I'm personally interested in potentially using this in Open Brush which is Apache 2.0 licenced so something compatible would be a great help.

**Comment by loOong-Cheng** [comment]
Hi. Thank you for your information. This repository is not licensed yet.

**Comment by andybak** [comment]
I suspect you mean "we haven't chosen a licence yet". All code is automatically copyrighted. It's a good idea to make your intent clear - many people assume that the lack of a licence on Github means "it's open source but we forgot to add a licence". If your intent is for this to be closed source then say that explicitly. (although, I would question why you haven't just made the repo private...). 

If you did want to make this open source than that it's usually as simple as picking between MIT and GPLv3
