### ISSUE TITLE
Performance compared to original PCX shaders

### ISSUE THREAD

**Issue by andybak** [loOong-Cheng/Adaptive-Shader-for-Point-Cloud-ply-#2]
Hi,

I've done a couple of rough unscientific benchmarks and I'm not seeing a huge speedup compared to the original disk shader with a resultant similar screen size.

I'm only testing on Desktop with a 3080 - am I like to see better relative performance with a Quest build?

**Comment by loOong-Cheng** [comment]
Hi. The speedup is generally not profound compared with the original disk shader. We try to adapt the size of the disk shader based on camera distance to the object so the visual experience might be better. Additionally, we tried neural rendering on this shader but it has decreased the frame rate to about 20 FPS.
